---
# Default labels for CUDN resources
default_subnet_labels:
  osac.openshift.io/managed-by: osac-fulfillment

# SecurityGroup NetworkPolicy defaults
default_security_group_labels:
  osac.openshift.io/managed-by: osac-fulfillment

# Layer2 defaults
default_layer2_role: Primary
default_ipam_lifecycle: Persistent
